name: 🍎 macOS Templates Builds
on: [push, pull_request]

# Global Settings
env:
  GODOT_BASE_BRANCH: 3.x
  SCONSFLAGS: platform=osx verbose=yes warnings=all werror=yes debug_symbols=no --jobs=2
  SCONS_CACHE_LIMIT: 4096

jobs:
  macos-template:
    runs-on: "macos-latest"
    name: Template (target=release, tools=no)

    steps:
      - uses: actions/checkout@v2

      # Upload cache on completion and check it out now
      - name: Load .scons_cache directory
        id: macos-template-cache-modules
        uses: actions/cache@v2
        with:
          path: ${{github.workspace}}/.scons_cache/
          key: ${{github.job}}-${{env.GODOT_BASE_BRANCH}}-modules-${{github.ref}}-${{github.sha}}
          restore-keys: |
            ${{github.job}}-${{env.GODOT_BASE_BRANCH}}-${{github.ref}}-${{github.sha}}
            ${{github.job}}-${{env.GODOT_BASE_BRANCH}}-${{github.ref}}
            ${{github.job}}-${{env.GODOT_BASE_BRANCH}}
        continue-on-error: true

      # Use python 3.x release (works cross platform)
      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          # Semantic version range syntax or exact version of a Python version
          python-version: '3.x'
          # Optional - x64 or x86 architecture, defaults to x64
          architecture: 'x64'

      # You can test your matrix by printing the current Python version
      - name: Configuring Python packages
        run: |
          python -c "import sys; print(sys.version)"
          python -m pip install scons
          python --version
          scons --version

      - name: Compile templates
        env:
          SCONS_CACHE: ${{github.workspace}}/.scons_cache/
        run: |
          scons target=release tools=no
          scons target=release_debug tools=no
          ls -l bin/
      - name: Zip Templates
        env:
          SCONS_CACHE: ${{github.workspace}}/.scons_cache/
        run: |
          cd bin
          cp ../misc/dist/osx_template.app .
          mkdir osx_template.app/Contents/MacOS
          cp godot.osx.opt.debug.64 osx_template.app/Contents/MacOS/
          cp godot.osx.opt.64 osx_template.app/Contents/MacOS/
          zip -r osx_3.4.beta_templates.zip osx_template.app/

      - uses: actions/upload-artifact@v2
        with:
          name: ${{ github.job }}
          path: bin/*
          retention-days: 14
      - name: Upload templates to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: bin/osx_3.4.beta_templates.zip
          asset_name: osx_3.4.beta_templates.zip
          tag: Godot-continuous-release
          overwrite: true
          body: "Bleeding edge release for those who like to live on the edge :)"
